### ISSUE TITLE
check balance next add wallet

### ISSUE THREAD

**Issue by AhrimanSefid** [meesvw/bitcoin-bruteforce#1]
hi 
thank you 
check balance next add wallet
https://www.homebitcoin.com/easybalance/

**Comment by meesvw** [comment]
Will add it in the [README.md](https://github.com/meesvw/bitcoin-bruteforce/blob/main/README.md) file.

**Comment by meesvw** [comment]
Updated the [README.md](https://github.com/meesvw/bitcoin-bruteforce/blob/main/README.md) file. Did not add the site you linked since it's last update was in 2020.

**Comment by AhrimanSefid** [comment]
which program mode is better? if reduce the number of wallets does it work faster?

**Comment by AhrimanSefid** [comment]
I have 64 cores CPU, I want to use your program with them. is it good? or can you suggest me better one?

**Comment by meesvw** [comment]
> which program mode is better? if reduce the number of wallets does it work faster?

OTBF is faster, but the amount of wallets will not impact the speed. I tested it a lot and tried to keep te speed as high as possible. However the only problem with this way of cracking is that it still needs to de 2^256 possibilities. 64 cores will work great with this program. There's probably faster options out there but I tried to make this one as fast as possible. Btcbf is a good option, but doesn't divide the load over several cores and it's only with random wallet generation.

So to conclude 64 cores is really good, the OTBF function is your best bet. But it will take time. Also you can add as many wallets as you like this will increase the chance to get a hit.

Hope this helps!
