### ISSUE TITLE
Bitcoin private key Recovery

### ISSUE THREAD

**Issue by Huntarh** [meesvw/bitcoin-bruteforce#10]
Hello,
please I need your help recovering my uncompressed Bitcoin private key which has 10 characters missing. I was wondering if you could help me write a python or any other code that will bruteforce the 10 missing characters in a fast loop like the image below and check the balance of the private key.

![ezgif-3-dbd0978ecd](https://user-images.githubusercontent.com/107959503/176828005-9e410ab5-a78a-4967-a735-179fd7304744.gif)

In the end if I find the correct private key I will give you some BTC.
let's talk on telegram

https://t.me/Huntarh
or email
ubongetimanthony@gmail.com

**Comment by meesvw** [comment]
Closing this issue with this code snippet:
```python
# define what you know here:
wif_string = 'K3HKezD4qqRKGtwc8d2d1Nw6vsoPDX9cMcUxqqMv'  # put the last chars here after the LK

# edit if you know what you're doing
import bit
import tqdm
import string
import itertools

char_string = string.ascii_letters + string.digits
possibilities = len(char_string)**10

print('Starting bruteforce process:\n')

for random_string in tqdm.tqdm(itertools.product(char_string, repeat=10), total=possibilities):
    try:
        key = bit.wif_to_key('LK' + ''.join(random_string) + wif_string)
        print('found: ', key.to_wif())
        break
    except ValueError:
        continue
```

You should install these packages or put them in a `requirements.txt`:
```python
bit
tqdm
```
