### ISSUE TITLE
performance comparison

### ISSUE THREAD

**Issue by dojo90** [meesvw/bitcoin-bruteforce#11]
I am currently using the following implementation (https://github.com/franzkruhm/Plutus-Scroo).
A stats output is also implemented there for comparison (https://github.com/franzkruhm/Plutus-Scroo/pull/18/commits/6dadfcfe573cceddc76e427153748d78344f546f).

This is currently `~5500 MPS` (misses per second) for me. Since I loaded around `33,165,253 bitcoin addresses`, that's ~182408891500 attempts per second (`1,82 * 10^11`).

Would it be possible to implement a performance tracker to compare the code for its performance?

**Comment by meesvw** [comment]
To answer your question, this is a tricky one. Since when I add a counter to the code the code will run slower (atleast that's what I've noticed). That's why I made a debug function and a normal function. I can add a function that will show the speed, but this will be slower and will slowly fill your ram up. I've ran one for a week with stats and after 7 days the RAM usage went up to 1GB which is a lot compared to the 50mb at the start.

I will create the function for you, but keep this in mind!

**Comment by AsicPrince** [comment]
> To answer your question, this is a tricky one. Since when I add a counter to the code the code will run slower (atleast that's what I've noticed). That's why I made a debug function and a normal function. I can add a function that will show the speed, but this will be slower and will slowly fill your ram up. I've ran one for a week with stats and after 7 days the RAM usage went up to 1GB which is a lot compared to the 50mb at the start.
> 
> I will create the function for you, but keep this in mind!

no need print output, just show how many address can be generate per second.

**Comment by meesvw** [comment]
I will try to get a speed estimate, however keep in mind that the speed depends on a lot of factors such as your CPU.

**Comment by meesvw** [comment]
These are the results on my CPU:

To put that into perspective if your CPU has 12 threads it can generate 12 * 10000 = 120000 addresses in 0.57~ seconds. So per second it will be 210000~ addresses generated.

Run with 10000 addresses generated:
```
0.5755994319915771
0.5796003341674805
0.5665972232818604
0.5730986595153809
0.5615971088409424
0.5831010341644287
0.572098970413208
0.5725998878479004
0.5720987319946289
0.5705983638763428
0.5650982856750488
0.5685985088348389
```

Run with 100000 addresses generated:
```
5.612470865249634
5.6079699993133545
5.6264731884002686
5.648477077484131
5.658978462219238
5.625473260879517
5.647978067398071
5.636975288391113
5.634974956512451
5.619972467422485
5.66398024559021
5.654479265213013
```

**Comment by dojo90** [comment]
Thanks for your research and comparison 👍

Your code can check around `1,73 * 10^4` keys/s per CPU
Plutus-Scroo  can check around `30,333333333 * 10^9` keys/s per CPU (I have 6 CPUs, so the result in the original question had to be divided by 6.)

If your calculations are correct, that's a brutal difference in performance.
