### ISSUE TITLE
Address sorting

### ISSUE THREAD

**Issue by Huntarh** [meesvw/bitcoin-bruteforce#12]
Hello,
Please I need your help with something. I have a big file containing 1million BTC Addresses both ones starting with 1, 3, and bc, so I was wondering if you could write a script to sort the addresses and saving them separately or sort out the ones starting with 1 and save in a txt file.

**Comment by meesvw** [comment]
Can you give me a sample of how the addresses are saved ? Are the sorted line for line or ?

**Comment by Huntarh** [comment]
It is sorted line for line

**Comment by meesvw** [comment]
This code snippet should do the job.

```python
import os

# open old file and read all lines
with open('old_file_name.txt', 'r') as file:
    all_wallets = file.readlines()

# check if wallets.txt exists
if not os.path.exists('wallets.txt'):
    with open('wallets.txt', 'w') as file:
        pass

# for wallet check if it starts with 1 and write to wallets.txt
with open('wallets.txt', 'a') as file:
    for wallet in all_wallets:
        if wallet.startswith('1'):
            file.write(wallet)

print('Done!')
```
