### ISSUE TITLE
problem with this program

### ISSUE THREAD

**Issue by Prrogrammer65** [meesvw/bitcoin-bruteforce#19]
If it finds a wallet program with balance, will wallet information be sent to you?

**Comment by meesvw** [comment]
No. The code will run locally on your device. You don't have to take my word for it, you can check the code in this Github repository! Hope this answers your question.

**Comment by Prrogrammer65** [comment]
How likely is it to find an address with a balance?I have heard that the person who finds an address with balance is the luckiest person in the world, is this true?

**Comment by meesvw** [comment]
Yes you have to be either incredibly lucky or have more time than stars in the universe.

**Comment by Prrogrammer65** [comment]
Thank you for taking the time to answer. The last question is that there is no found.txt file, if the program finds it, will this file be created automatically?are you sure?

**Comment by meesvw** [comment]
Yes I tested it multiple times by generating the same address using the int. This way I could test if the file was created and properly updated!

**Comment by Prrogrammer65** [comment]
![Screenshot_۲۰۲۳۰۱۳۱-۰۰۵۲۱۹_Termius](https://user-images.githubusercontent.com/123581181/216385845-153f00d4-dacb-40fc-a4b0-55b51b32b931.jpg)
After three months passed, one of the servers did not print the address, probably it was with Bance, it did not create any file. I turned off the system. What is the reason?

**Comment by meesvw** [comment]
Let me look into it, I will probably do an update if I find something or make the feedback more strict!

**Comment by meesvw** [comment]
However I can assure you that it didn't find any address with balance since it will explicitly print it out.

**Comment by meesvw** [comment]
I updated the repo, let me know if this solves the issue.

**Comment by Prrogrammer65** [comment]
I stopped the program as soon as the problem occurred, is it possible to get the unprinted address from the history of the program? What is the reason for this problem?

**Comment by meesvw** [comment]
I am certain the program did not generate an address.

**Comment by Prrogrammer65** [comment]
Can you save all the generated urls in a txt file together at all?

**Comment by meesvw** [comment]
You can but that will take an enormous amount of space. Since you use a phone I do not recommend this option.

**Comment by Prrogrammer65** [comment]
I use the phone to connect to the server, the storage space is 5 tb, please add this option

**Comment by Prrogrammer65** [comment]
![Screenshot_۲۰۲۳۰۲۱۱-۰۰۱۱۲۱_Termius](https://user-images.githubusercontent.com/123581181/218335638-e0361c90-d879-45cf-9edd-97efc747d843.jpg)
This error in each 4 days.please slove

**Comment by meesvw** [comment]
This seems like an issue from your side. I cannot recreate your issue unfortunaly.

**Comment by Prrogrammer65** [comment]
![Screenshot_۲۰۲۳۰۲۱۶-۲۳۵۸۳۱_Termius](https://user-images.githubusercontent.com/123581181/221028488-a00b010a-513d-4b67-b8d6-1229ec3f2f47.jpg)
Again balance not show

**Comment by meesvw** [comment]
![image](https://user-images.githubusercontent.com/73003273/221036849-eb81ff21-fa05-480c-a871-03d7cce21fed.png)

You can manually check the balance since it will always print the generated address :)

**Comment by meesvw** [comment]
I will close this issue, the problem has been resolved with a workaround.
