### ISSUE TITLE
Running issue 

### ISSUE THREAD

**Issue by isaacfth** [meesvw/bitcoin-bruteforce#23]
Hi, I am having an issue when I try to run the program, first of all, I couldn't install the requirements it says " ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'", Seconds when I try to run the program it says  "can't open the file, No such file or directory", Knowing I am using Chromebook and I am trying to run the program on Linux.

**Comment by meesvw** [comment]
Did you put the script in the same folder as the requirements.txt file ?

**Comment by meesvw** [comment]
I will close this as no further activity has occured.
