### ISSUE TITLE
Large wallets.txt file problems?

### ISSUE THREAD

**Issue by WHYYTE674** [meesvw/bitcoin-bruteforce#4]
is there a problem with a large wallets.txt file ? how can the script check the generated wallet with a large wallets.txt so fast ?
and can you please explain more how the script is working exactly? maybe to put it in readme too

is cpu or gpu faster? did u test it?
can u run the script on the cpu cores multiple times? without errors?
tell us, what you mean by : 
" optimized traditional bruteforce
# Will try every INT between 10**75 and max possibility.
# This methode is based on the best practice to get the safest address possible.
def OTBF(r, sep_p):
    sint = (sep_p * r) + 10 ** 75 if r == 0 else (sep_p * r)
    mint = (sep_p * (r + 1)) "

**Comment by meesvw** [comment]
**1. Is there a problem with a large wallets.txt file?**
The only downside I know of is that if the `wallets.txt` file gets bigger it will increase the ram used to load it (and possibly the matching speed). What happens is that the wallets file gets read and assigned as a string. Based on some testing the now assigned string will be matched against a generated wallet. If that wallet address is in the string there is a match.

Example:
```python
if pk.address in wallets:
```

**Can you please explain how the script is working?**
The scripts offers 2 kinds of functions. The first function being a random generator. The `bit` library offers a way to generate private keys based of integers. This function will randomly generate integers in between 1 and the max possible number (which is really large).

The second function will generate every wallet based on the integers between 1 and the max possible number. This will generate every wallet possible. However this will take an enormous amount of time. Therefor I made a function which will start from a higher number cutting the amount of wallets needed to generate. The chance that someone will take a bitcoin address with 1 as number is really small (or that person is not aware of the risk). So people will tend to go with higher numbers to decrease the chance that someone will generate their private key.

**Is cpu or gpu faster? did u test it?**
GPU will be faster, but the integration with Python was not made for AMD GPUs. If I get the chance I will create a library for NVIDIA. If I can optimize the code to run faster I will update this repo.

**Can u run the script on the cpu cores multiple times? without errors?**
Yes, the script should have no errors I'm aware of. If you encounter an error please open a issue.


Hope this answers your questions.

**Comment by wmcorless** [comment]
I wrote a similar program in Node. However I have been interested in making it work on GPUs as well. CUDA seems like a good way to go.
