### ISSUE TITLE
GPU implementation

### ISSUE THREAD

**Issue by DasT1er** [meesvw/bitcoin-bruteforce#5]
Can you make a feature where you can see the h/s and how long can it last?
Or can you make it that all cores working at one address?
And that my gpu can work on it too? I have an Amd card

**Comment by meesvw** [comment]
I am working on a implementation for the GPU. However so far I haven't found a way to make it work... For the hash rate. I will make a seperate function, because it will decrease performance and so far I've noticed that it leaks into your ram usage. They are on my todo list!

**Comment by meesvw** [comment]
For now this function will not be possible. Therefor I will close this issue.
